import React from 'react'
import { Container, ContainerImage, ContainerText, Wrapper } from "../About/AboutElement"
import about from '../../assets/about.png'
import Skills from './Skills'
const About = () => {
  return (
    <>
        <Wrapper>
        <h1>About Me</h1>
            <Container>
               <ContainerText>
                  <p><strong>Hi <span>&#x1F44B;</span></strong><br/> I'm Abiodun Segun <span> a Web Developer & Business Entrepreneur</span> living in Lagos, Nig.<br/> I craft Ideas and build on ideas generated by client into interactive web apps.</p>
                  <p>If you need an Web presence for your business or an employer looking to hire you can get in touch with me<span> here</span></p>

                  <Skills/>
                  
               </ContainerText>
               <ContainerImage>
                  <img src={about} alt="my_image"/>
               </ContainerImage>
            </Container>
        </Wrapper>
    </>
  )
}

export default About